#!/usr/bin/env sh

base_dir=$(dirname $0)
prerequisites_dir=${base_dir}/Prerequisites

__log()
{
    echo prerequisite: $* >&2
}

__run()
{
    __log $*
    $*
}

__get_archive()
{
    local url=$1
    local archive="${prerequisites_dir}/$2"
    
    if [[ ! -f "${archive}" ]]; then
        __run curl -o "${archive}" --compressed -L "${url}"
    else
       __log exists: "${archive}"
    fi
}

__extract_from_tarball()
{
    local archive="${prerequisites_dir}/$1"
    local dir="${prerequisites_dir}/$2"
    
    if [[ ! -d "${dir}" ]]; then
        toplevel_dir=${prerequisites_dir}/$(tar tzf "${archive}" | head -1)
        __run tar -C "${prerequisites_dir}" -xzf "${archive}"
        __run mv "${toplevel_dir}" "${dir}"
    else
        __log exists: "${dir}"
    fi
}

__fetch_tarball()
{
    __get_archive "$1" "$2"
    __extract_from_tarball "$2" "$3"
}

__svn_checkout()
{
    if [[ ! -d "${2}" ]]; then
        __run svn co "${1}" "${2}"
    else
        __log exists: "${2}"
    fi
}






if [[ ! -d "${prerequisites_dir}" ]]; then
    __run mkdir "${prerequisites_dir}"
fi

__fetch_tarball "https://github.com/pokeb/asi-http-request/tarball/v1.8" "ASIHTTPRequest-v1.8.tar.gz" "ASIHTTPRequest"
__fetch_tarball "https://github.com/stig/json-framework/tarball/v3.0beta1" "JSON-v3.0beta1.tar.gz" "JSON"

ocmock_dir="${prerequisites_dir}/OCMock"
__svn_checkout "http://svn.mulle-kybernetik.com/OCMock/trunk@77" "${ocmock_dir}"
ocmock_lib="${ocmock_dir}/Source/build/Debug/Library/libOCMock.a"
if [[ ! -f "${ocmock_lib}" ]]; then
    (cd "${ocmock_dir}/Source" && __run xcodebuild -configuration Debug -target OCMockLib)
else
    __log exists: "${ocmock_lib}"
fi

#__svn_checkout "http://google-toolbox-for-mac.googlecode.com/svn/trunk@439" "${prerequisites_dir}/GoogleToolboxForMac"
